name: onsunday_forum
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.4
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^8.1.6
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  get_storage: ^2.1.1
  path_provider: ^2.1.5
  device_preview: ^1.2.0
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lang/en.json
    - assets/lang/vi.json

